algoritmo "SomaParametrosReferencia"

var
      X, Y: inteiro
procedimento Soma (var A, B: inteiro)
inicio
      A <- A + 1
      B <- B + 2
      Escreval ("Valor de A = ", A)
      Escreval ("Valor de B = ", B)
      Escreval ("Soma A + B =", A+B)
fimprocedimento
inicio
      X <- 4
      Y <- 8
      Soma (X, y)
      Escreval ("Valor de X = ", X)
      Escreval ("Valor de Y = ", Y)
      Escreval ("Soma X + Y = ", X+Y)
fimalgoritmo
